apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-postgres-pvc
spec:
  storageClassName: {{ .Release.Name }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
